version: "3"

services:

  nxs:
    # image: node:12.3-alpine
    build: "."
    # command: sh -c "npm start"
    environment:
      - NODE_ENV=development
      - PORT=8002
    ports:
      - "8002:8002"