version: "3"

services:

  nxs:
    build: "."
    # image: node:12.3-alpine
    # command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - PORT=8002
    ports:
      - "8002:8002"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app:cached
    