version: "3"

services:

  nxs:
    build: "."
    # image: node:12.3-alpine
    # command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - PORT=8002
    ports:
      - "8002:8002"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      # Need to read https://stackoverflow.com/questions/51097652/install-node-modules-inside-docker-container-and-synchronize-them-with-host
      - /home/node/app/node_modules
    